### ISSUE TITLE
Handle incomplete Nowsecure assessments

### ISSUE THREAD

**Issue by sgkiokas** [camelotls/actions-nowsecure#59]
When an assessment hasn't been been completed for some reason, the action throws the following:

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at startAnalysis (/index.js:59:85)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /index.js:140:3
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

The way it has been designed prevents the action for blowing up, however, we need to somehow inform the end user about the issue.

**Comment by pmegremis** [comment]
https://github.com/camelotls/actions-nowsecure/pull/86
